# .github/workflows/cd.yml
name: CD - Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_FILE }}" > $HOME/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install demo ./helm-chart \
            --set image.repository=your-dockerhub-username/demo-app \
            --set image.tag=1.0
